create table stats (
	seas_id int not null,
	season int not null,
	player_id int not null,
	player varchar not null,
	birth_year varchar,
	pos varchar,
	age int,
	experience int,
	lg varchar(3),
	tm varchar(3),
	g int,
	gs int,
	mp_per_game float,
	fg_per_game float,
	fga_per_game float,
	fg_percent float,
	x3p_per_game float,
	x3pa_per_game float,
	x3p_percent float,
	x2p_per_game float,
	x2pa_per_game float,
	x2p_percent float,
	e_fg_percent float,
	ft_per_game float,
	fta_per_game float,
	ft_percent float,
	orb_per_game float,
	drb_per_game float,
	trb_per_game float,
	ast_per_game float,
	stl_per_game float,
	blk_per_game float,
	tov_per_game float,
	pf_per_game float,
	pts_per_game float,
	primary key(seas_id)
);

create table all_star_selections (
	player varchar not null,
	team varchar not null,
	lg varchar(3),
	season int not null,
	replaced boolean,
	primary key(player, season)
);

create table advanced_stats (
	seas_id int not null,
	season int not null,
	player_id int not null,
	player varchar not null,
	birth_year varchar,
	pos varchar,
	age int,
	experience int,
	lg varchar(3),
	tm varchar(3),
	g int,
	mp float,
	per float,
	ts_percent float,
	x3p_ar float,
	f_tr float,
	orb_percent float,
	drb_percent float,
	trb_percent float,
	ast_percent float,
	stl_percent float,
	blk_percent float,
	tov_percent float,
	usg_percent float,
	ows float,
	dws float,
	ws float,
	ws_48 float,
	obpm float,
	dbpm float,
	bpm float,
	vorp float,
	primary key(seas_id),
	foreign key(seas_id) references stats(seas_id)
);

create table award_teams (
	season int not null,
	lg varchar(3),
	award_type varchar not null,
	number_tm varchar(3) not null,
	player varchar not null,
	player_position varchar(2),
	seas_id int not null,
	player_id int not null,
	birth_year int,
	tm varchar(3),
	age int,
	primary key(seas_id, award_type),
	foreign key(seas_id) references stats(seas_id)
);